name: 'Glitch Merge to Main'
#ATTENTION! In order for this action to work, delete from this line...
description: 'Edit your files on Glitch, and this action will merge all your changes to your main branch as soon as you export your project'
author: 'Leonardo Zuniga https://github.com/leozusa/Glitch-Merge-To-Main'
branding:
  icon: git-merge
  color: blue
#...all the way to this line, and place in your .github/workflows/ folder
on:
  push:
    branches: [ glitch ]
jobs:
  mergetomaster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.repos.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_message: context.payload.head_commit.message,
              head: 'glitch',
              base: 'main',
            });
